### ISSUE TITLE
사용자의 프로필을 누르면 해당 사용자의 게시글을 볼 수 있도록 하는 API

### ISSUE THREAD

**Issue by yy0867** [FirstianB101/reciptopia-server#2]
인스타그램이나 페이스북 같은 앱들은 게시글이나 댓글을 작성한 사람들의 프로필을 누르면 해당 작성자의 정보를 볼 수 있는데,

우리도 `Board + Comment`가 owner를 알고, `Account`에는 해당 계정의 `Set<Board>`가 있으므로

`Board + Comment`의 owner이 작성한 `Set<Board>`를 조회할 수 있는 기능을 제공하면 어떨까 생각함

물론 방금 생각한 것이어서 급하고 중요한 기능들 먼저 하고 나중에 생각해봐도 좋을듯

**Comment by tellang** [comment]
사용자의 프로필을 누르면 해당 사용자의 게시글을 볼 수 있도록 하는 API라는게 그냥 기본적인 계정 조회 API를 클라이언트에서 특정 순간에 사용하는거랑 다른거야?

**Comment by yy0867** [comment]
만약 토큰 인증같은걸 한다 하면 유저가 다른 유저의 account의 board를 못 보는 상황이 있을 수도 있지 않나?

**Comment by tellang** [comment]
만약 그렇게 만든다면 기능이 같은데 권한이 다른상황인데, 그럼 잘못만든게 아닐까

**Comment by yy0867** [comment]
그러네 그럼 

> 사용자의 프로필을 누르면 해당 사용자의 게시글을 볼 수 있도록 하는 API라는게 그냥 기본적인 계정 조회 API를 클라이언트에서 특정 순간에 사용하는거랑 다른거야?

이걸로 해주셈
